name: layout_pmhdv
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  syncfusion_flutter_charts: ^27.1.58
  intl: ^0.18.1
  fl_chart: ^0.65.0
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/